### ISSUE TITLE
vue-cli4, 打包后，样式丢失

### ISSUE THREAD

**Issue by DengRiGuang** [element-plus/unplugin-element-plus#10]
复现例子：
[https://github.com/DengRiGuang/micro-main.git](url)

**Comment by lctech-Neil** [comment]
Hi @DengRiGuang ,

可以參考我在，#4 的回覆，希望能對你有幫助

https://github.com/element-plus/unplugin-element-plus/issues/4#issuecomment-929303788

**Comment by DengRiGuang** [comment]
@lctech-Neil 
var transformImportStyle = (specifier, source, useSource = false, options) => {
  const { prefix, lib, format } = options;
  const statement = source.substring(specifier.ss, specifier.se);
  const leftBracket = statement.indexOf("{");
  if (leftBracket > -1) {
    const identifiers = statement.slice(leftBracket + 1, statement.indexOf("}"));
    const components = identifiers.split(",");
    const styleImports = [];
    components.forEach((c) => {
      const trimmed = c.trim();
      if (trimmed.startsWith(prefix)) {
        const component = trimmed.slice(prefix.length);
        if (useSource) {
          styleImports.push(`import '${lib}/${formatMap[format]}/components/${hyphenate(component)}/style'`);
        } else {
          styleImports.push(`import '${lib}/${formatMap[format]}/components/${hyphenate(component)}/style/css'`);
        }
      }
    });
    return styleImports.join("\n");
  }
};
是指修改插件的样式引入路径嘛？

**Comment by sxzz** [comment]
fixed in https://github.com/element-plus/element-plus/pull/3721
