### ISSUE TITLE
Import with comments

### ISSUE THREAD

**Issue by crown-cc** [element-plus/unplugin-element-plus#140]
如果在 import { } from 'element-plus' 中使用了注释，可能会导致 transform 异常。

下面的例子是用 vue-cli 初始化的项目使用 element-plus + unplugin-element-plus。

![image](https://user-images.githubusercontent.com/51734557/161209101-a158e2e8-edd4-4f08-b54a-de42272d7b30.png)

![image](https://user-images.githubusercontent.com/51734557/161209323-06487174-95c3-403f-be35-9482ec7e108f.png)

猜测在 example 里的 vite 的例子是，当使用 vite2 + vue3 + ts 时，@vitejs/plugin-vue 是使用了 esbuild 去除了注释。[vite](https://github.com/vitejs/vite/blob/main/packages/plugin-vue/src/main.ts#L201)

是否需要进行注释过滤？ [Commit](https://github.com/crown-cc/unplugin-element-plus/commit/84695532152dcd2dc9523b864125efce35f62fcf)

**Comment by sxzz** [comment]
Fixed, thanks!

**Comment by crown-cc** [comment]
您好，我是黄瞻程。我已收到您的来信，将尽快给您回复。谢谢。祝您生活愉快！
