### ISSUE TITLE
为什么我安装了到vite 里面

### ISSUE THREAD

**Issue by yemaozi999** [element-plus/unplugin-element-plus#141]
![image](https://user-images.githubusercontent.com/16147749/161377592-ee33946d-b758-48c2-a44b-83c1d6221a0d.png)

但是"element-plus" 还是报红

**Comment by sxzz** [comment]
还需要安装 element-plus 依赖，请参考文档 https://element-plus.org/zh-CN/guide/installation.html#%E4%BD%BF%E7%94%A8%E5%8C%85%E7%AE%A1%E7%90%86%E5%99%A8
