### ISSUE TITLE
unplugin-element-plus的options类型中有一个 defaultLocale 有什么用呀

### ISSUE THREAD

**Issue by GamesSoul** [element-plus/unplugin-element-plus#144]
看了下源码里的[transform.ts](https://github.com/element-plus/unplugin-element-plus/blob/main/src/core/transform.ts)文件没有使用这个api  可以告诉我这个api是有什么用么

**Comment by sxzz** [comment]
暂时没用，本来是打算提供一个选项，替换默认的英语
