### ISSUE TITLE
样式文件丢失

### ISSUE THREAD

**Issue by aclowner** [element-plus/unplugin-element-plus#147]
用你们的新的东西真是费劲，这稳定性不知道比之前差了多少了

[vite] Internal server error: Failed to resolve import "element-plus/es/components/column/style/css" from "src\components\home\InfoItem3.vue". Does the file exist?

**Comment by JeremyWuuuuu** [comment]
1. We did not take your money.
2. We are doing FOSS here.
3. You do not get to talk s**t in my repo.
4. There are search engines out there.
5. You are banned from this organization 🙃
