### ISSUE TITLE
defaultLocale 什么时候可用，为什么配置了还是英文

### ISSUE THREAD

**Issue by mxp131011** [element-plus/unplugin-element-plus#151]
```
 ElementPlusPlugin({ useSource: true, defaultLocale: 'zh-cn' })
```
这样是否可替换默认语言为中文还是我配置错了 ,替换后是否可以不用在`<el-config-provider>`中配置`locale` ，我用的是`vite`

**Comment by sxzz** [comment]
Please refer to the example in this repo.
Or provide a mini reproduction.
https://antfu.me/posts/why-reproductions-are-required-zh
