### ISSUE TITLE
Bug hover date-picker with router

### ISSUE THREAD

**Issue by arnauddoub** [element-plus/unplugin-element-plus#155]
When I hover the Datepicker it expands but if I remove vue-router it does not expand. The order of loading the files is not good

Reproduction:
https://stackblitz.com/edit/vitejs-vite-z7jgxg

https://user-images.githubusercontent.com/14277978/184155038-53bf2abd-ac2c-4b26-a003-d9ca9e1aea87.mov

**Comment by sxzz** [comment]
This is repository of unplugin, please new a new issue to [element-plus](https://github.com/element-plus/element-plus) main repo.
