### ISSUE TITLE
[Question] unplugin-vue-components 与 unplugin-element-plus

### ISSUE THREAD

**Issue by aboutZZ** [element-plus/unplugin-element-plus#159]
`unplugin-vue-components`内置了`ElementPlusResolver`，使用这个后是否还有必要使用本插件`unplugin-element-plus`？

**Comment by sxzz** [comment]
You can choose either one.
二选一即可

**Comment by mrxu0** [comment]
发现内置的 ElementPlusResolver 不能够解决 import { ElMessage } from "element-plus"; 的样式引入问题
