### ISSUE TITLE
Cannot find module 'unplugin-element-plus/vite' or its corresponding type declarations.

### ISSUE THREAD

**Issue by yxb94616** [element-plus/unplugin-element-plus#189]
VsCode Version: 1.77.1 
Node.js: 16.14.2
OS: Windows10 x64 10.0.19045

"vite": "^4.2.1"
"unplugin-element-plus": "^0.7.0"
"typescript": "^4.9.5"

在vite中使用：

`import ElementPlus from "unplugin-element-plus/vite";`

报了一个 typescript 错误：

`Cannot find module 'unplugin-element-plus/vite' or its corresponding type declarations.`

**Comment by sjqw** [comment]
我也遇到了同样的错误,求解决方式

**Comment by heyongsheng** [comment]
@sjqw @yxb94616  我也遇到了这个问题，暂时没找到很好的解决方案，但我找到了别的办法，因为我之前的项目这么写是没问题的，所以我查看了版本号，之前的安装的是0.4.1的，所以如果你也不知道怎么解决，安装0.4.1版本可能是一个不错的办法，或者直接使用`// @ts-ignore`忽略这一行的报错

```
npm i unplugin-element-plus@0.4.1 -D
// or

// @ts-ignore
import ElementPlus from 'unplugin-element-plus/vite'
```

**Comment by L-T-G** [comment]
同上，也遇到了这个问题

**Comment by skyclouds2001** [comment]
同上，我也遇到了这个问题

OS: Windows10 x64
IDE：WebStorm 2023.1
Node：18.13.0

vite：4.2.1
typescript：5.0.2
unplugin-element-plus：0.7.0

**Comment by yxb94616** [comment]
@sjqw @heyongsheng @L-T-G @skyclouds2001 
已找到解决这个问题的方法，在你使用的 tsconfig*.json 下的 compilerOptions 中添加如下属性/值：

`"moduleResolution": "bundler"`

造成这个错误的原因是因为 typescript 的模块解析策略问题，有兴趣可以了解一下，推荐几篇文章：

[https://www.typescriptlang.org/docs/handbook/module-resolution.html](url)
[https://juejin.cn/post/7221551421833314360](url)

**Comment by Allihol** [comment]
> 

使用这个配置后，从element-plus导出的组件类型找不到了。
import type { FormInstance } from 'element-plus'
// 模块"element-plus"没有导出的成员"FormInstance"

**Comment by yxb94616** [comment]
> "moduleResolution": "bundler" 使用这个配置后，从element-plus导出的组件类型找不到了。 import type { FormInstance } from 'element-plus' // 模块"element-plus"没有导出的成员"FormInstance"

我这里没有这个问题呐
![image](https://user-images.githubusercontent.com/20277731/236425289-31f8825a-3680-4625-ac42-e7c0e16aaef8.png)

**Comment by yxb94616** [comment]
> > > "moduleResolution": "bundler" 使用这个配置后，从element-plus导出的组件类型找不到了。 import type { FormInstance } from 'element-plus' // 模块"element-plus"没有导出的成员"FormInstance"
> > 
> > 
> > 我这里没有这个问题呐 ![image](https://user-images.githubusercontent.com/20277731/236425289-31f8825a-3680-4625-ac42-e7c0e16aaef8.png)
> 
> 你的package.json中有type:"module"吗

没有呢

**Comment by Allihol** [comment]
> > > > "moduleResolution": "bundler" 使用这个配置后，从element-plus导出的组件类型找不到了。 import type { FormInstance } from 'element-plus' // 模块"element-plus"没有导出的成员"FormInstance"
> > > 
> > > 
> > > 我这里没有这个问题呐 ![image](https://user-images.githubusercontent.com/20277731/236425289-31f8825a-3680-4625-ac42-e7c0e16aaef8.png)
> > 
> > 
> > 你的package.json中有type:"module"吗
> 
> 没有呢

难搞，我已经通过回退至0.4.1解决了

**Comment by kisekiremi** [comment]
just add  // @ts-ignore

**Comment by skyclouds2001** [comment]
> just add // @ts-ignore

if using @ts-ignore to disable this ts error, @ts-expect-error is much better

**Comment by SATHISH099** [comment]
> > just add // @ts-ignore
> 
> if using @ts-ignore to disable this ts error, @ts-expect-error is much better

Yeah!👍 we expected for more better! @element-bot #unplugin-element-plus

**Comment by sxzz** [comment]
Try the latest `unplugin-element-plus@0.9.0`.
