### ISSUE TITLE
为什么会提示 找不到模块“unplugin-element-plus/vite”或其相应的类型声明

### ISSUE THREAD

**Issue by Maxiaochuan123** [element-plus/unplugin-element-plus#195]
packge.json ↓↓↓↓↓↓↓↓
"unplugin-element-plus": "^0.7.1"

vite.config.js ↓↓↓↓↓↓↓↓
import ElementPlus from 'unplugin-element-plus/vite'

plugins: [
  ElementPlus({ useSource: true })
]

**Comment by li-junpeng** [comment]
用这个

`import ElementPlus from 'unplugin-element-plus/dist/vite'`

**Comment by KZ137onethe** [comment]
我也遇到了这个问题， @sxzz 能不能看下这个问题
unplugin-element-plus | vesion: 0.8.0
![image](https://github.com/user-attachments/assets/caeecf0f-0c60-4f44-b0ad-0e6027532083)

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by sxzz** [comment]
Try the latest `unplugin-element-plus@0.9.0`.
