### ISSUE TITLE
Failed to resolve import "fsevents" from "node_modules/unplugin-element-plus/dist/vite.mjs"

### ISSUE THREAD

**Issue by sucheep-s** [element-plus/unplugin-element-plus#197]
OS: 18.04.6 LTS 
Node: v16.13.2

I'm not able to run the application on Ubuntu server I got below error,

Nuxt 3.7.1 with Nitro 2.6.2                                                                                                                                                                 5:48:20 AM
                                                                                                                                                                                            5:48:21 AM
  ➜ Local:    http://localhost:5000/
  ➜ Network:  use --host to expose

ℹ Using default Tailwind CSS file                                                                                                                                         nuxt:tailwindcss 5:48:24 AM
ℹ Tailwind Viewer: http://localhost:5000/_tailwind/                                                                                                                       nuxt:tailwindcss 5:48:24 AM
[nuxt] Could not resolve id fsevents /home/thor/project/web-frontend/node_modules/unplugin-element-plus/dist/vite.mjs                                                               5:48:34 AM

 ERROR  Failed to resolve import "fsevents" from "node_modules/unplugin-element-plus/dist/vite.mjs". Does the file exist?                                                                   5:48:34 AM

ℹ Vite client warmed up in 8951ms                                                                                                                                                          5:48:36 AM
✔ Nitro built in 4867 ms 

How could I solved it ?

**Comment by sxzz** [comment]
Try the latest `unplugin-element-plus@0.9.0`.
