### ISSUE TITLE
install   error?

### ISSUE THREAD

**Issue by tfish-oh** [element-plus/unplugin-element-plus#198]
![image](https://github.com/element-plus/unplugin-element-plus/assets/16274637/581b3b35-c57d-47ec-bf9b-771a8b944e47)

**why install    show this github login  dialog ?**

**Comment by TheNovemberRain** [comment]
try `npm i unplugin-element-plus`

**Comment by sxzz** [comment]
Try the latest `unplugin-element-plus@0.9.0`.
