### ISSUE TITLE
package of npm is old?

### ISSUE THREAD

**Issue by Half-A-Turnip** [element-plus/unplugin-element-plus#3]
![image](https://user-images.githubusercontent.com/24860389/133451683-15bd73a3-bd9b-4504-b948-efdad567cfdb.png)
not download 0.1.0

**Comment by sxzz** [comment]
Yeah, I will publish this package tomorrow.

**Comment by mxp131011** [comment]
You let me white happy one time!

**Comment by Half-A-Turnip** [comment]
谢谢，不过我发现了个问题。英文不太好，下面的问题我就用中文描述了。
vite开发环境样式是正常，但是打包后，除了app.vue引入的组件样式被打包进来了，其他（路由懒加载）的样式都没有打包进来。
和vite-plugin-element-plus一样的问题。我试着修改你们的插件，按需加载时候引入我本地的scss，成功了。
![image](https://user-images.githubusercontent.com/24860389/133454380-1da1d2b9-53fa-4580-b74c-8d313ad3a631.png)

**Comment by Half-A-Turnip** [comment]
> 谢谢，不过我发现了个问题。英文不太好，下面的问题我就用中文描述了。
> vite开发环境样式是正常，但是打包后，除了app.vue引入的组件样式被打包进来了，其他（路由懒加载）的样式都没有打包进来。
> 和vite-plugin-element-plus一样的问题。我试着修改你们的插件，按需加载时候引入我本地的scss，成功了。
> ![image](https://user-images.githubusercontent.com/24860389/133454380-1da1d2b9-53fa-4580-b74c-8d313ad3a631.png)
样式问题入下图
![image](https://user-images.githubusercontent.com/24860389/133454601-df86f88c-63fb-44d5-a98f-224d9c2260ef.png)

**Comment by sxzz** [comment]
@Half-A-Turnip Could you please provide a minimum reproduce repository? Thanks.

**Comment by sxzz** [comment]
Also, please create an new issue for this problem.

**Comment by Half-A-Turnip** [comment]
> Also, please create an new issue for this problem.

ok，thanks

**Comment by sxzz** [comment]
@Half-A-Turnip Released.

**Comment by sxzz** [comment]
@Half-A-Turnip Released.

**Comment by Half-A-Turnip** [comment]
thanks
