### ISSUE TITLE
vite:import-analysis: Failed to resolve import '.../index';

### ISSUE THREAD

**Issue by popojja** [element-plus/unplugin-element-plus#36]
报错：
![image](https://user-images.githubusercontent.com/26264748/142796856-caa8aaa5-7adc-4df5-87bb-49b6acd3b9f6.png)

组件下的目录是这样的
![image](https://user-images.githubusercontent.com/26264748/142797052-777e3b41-d77a-4708-9848-355d3bf9d448.png)

问题差不多就是，vite:import-analysis 读不到index.mjs。

遂改源码：
![image](https://user-images.githubusercontent.com/26264748/142797346-d8598c02-836b-439f-a886-14b5a3e1cfca.png)

虽然问题完美解决，但仍然希望官方改进一下。
不想自己的代码里面有很多奇怪的外部代码被追踪到。

**Comment by popojja** [comment]
另外：
当我尝鲜<script setup>写法调用loading指令的时候，就很尴尬
![image](https://user-images.githubusercontent.com/26264748/142797995-26777c77-6c29-4fe0-8048-fafee0246bbd.png)
![image](https://user-images.githubusercontent.com/26264748/142798191-e3341338-e474-4044-853b-ca7bc35e262d.png)

我不得不这么干：
![image](https://user-images.githubusercontent.com/26264748/142798373-fe3a9a5e-16cf-46e5-8987-b02e4e97a7c4.png)
<script setup>带来的快乐，当场少了一半

**Comment by sxzz** [comment]
对于第二个问题，个人建议使用 https://github.com/antfu/unplugin-vue-components，已支持指令。

**Comment by popojja** [comment]
> 对于第二个问题，个人建议使用 [https://github.com/antfu/unplugin-vue-components，已支持指令。](https://github.com/antfu/unplugin-vue-components%EF%BC%8C%E5%B7%B2%E6%94%AF%E6%8C%81%E6%8C%87%E4%BB%A4%E3%80%82)

哇！非常感谢。
这个插件解决了以上所有问题，还免除了import，组件可以直接使用并自动按需引入。
真香！

**Comment by sxzz** [comment]
@popojja 如果方便的话，能否提供一个能复现的仓库地址，毕竟这个插件还是要维护的。
