### ISSUE TITLE
Some styles are lost after packaging（打包之后部分样式丢失）

### ISSUE THREAD

**Issue by Half-A-Turnip** [element-plus/unplugin-element-plus#4]
vite开发环境样式是正常，但是打包后，除了app.vue引入的组件样式被打包进来了，其他（路由懒加载）的样式都没有打包进来。
这个是问题还原库的链接。因为插件还没有发布npm，所以这个是我下载源码编译的unplugin-element-plus。
https://github.com/Half-A-Turnip/element-plus-no-build-css.git
很感谢你们的解答

**Comment by Half-A-Turnip** [comment]
> vite开发环境样式是正常，但是打包后，除了app.vue引入的组件样式被打包进来了，其他（路由懒加载）的样式都没有打包进来。
> 这个是问题还原库的链接。因为插件还没有发布npm，所以这个是我下载源码编译的unplugin-element-plus
> https://github.com/Half-A-Turnip/element-plus-no-build-css.git

**Comment by zongzi531** [comment]
I clone your depository, i find this bug occurred during the "Vite rendering chunks" phase, maybe related to https://github.com/vitejs/vite/issues/4840 .

**Comment by Half-A-Turnip** [comment]
@zongzi531 let me try,thanks

**Comment by zongzi531** [comment]
@Half-A-Turnip I think, maybe need fix `../` in element-plus.

For example checkbox:

```ts
import '../../../components/base/style/css';
import '../../../../theme-chalk/el-checkbox.css';

// changeto

import 'element-plus/es/components/base/style/css'; // import 'element-plus/theme-chalk/base.css';
import 'element-plus/theme-chalk/el-checkbox.css';
```

**Comment by Half-A-Turnip** [comment]
@zongzi531 i tried,but it has no effect. now i copy theme-chalk and  modify the vite-plugin-element-plus to fix this problem.
this seems to be a stupid way . haha
还是很感谢，杭州的老铁

**Comment by lctech-Neil** [comment]
@Half-A-Turnip ,

建議改成會比較好：
```javascript
// ** 為你要的 css
 import 'element-plus/theme-chalk/**.css' 
```

主要是因為 element ui 的 package.json 的 sideEffects 設定只有開放三個路徑，其他的都會被 shaking 掉。

```json
"sideEffects": [
    "dist/*",
    "theme-chalk/*.css",
    "theme-chalk/src/*.scss"
  ],
```

如果是類似  import 'element-plus/es/components/table/style/css.js' 這類的話，在webpack 編譯的時候都會被去除。
所使用的 element ui版本: element-plus: "1.1.0-beta.17"

希望對你有幫助 。

**Comment by sxzz** [comment]
fixed in https://github.com/element-plus/element-plus/pull/3721
