### ISSUE TITLE
新增自动按需引入功能

### ISSUE THREAD

**Issue by jayfongs** [element-plus/unplugin-element-plus#7]
element plus 1.1.0 破坏性改动后 导致 [vite-plugin-components](https://github.com/antfu/vite-plugin-components) 插件目前还没有更新，也不清楚后续会不会维护。

现在element plus官方有了按需引入的插件，所以能否实现像[vite-plugin-components](https://github.com/antfu/vite-plugin-components)插件一样无脑自动按需引入功能？

目前用过这种方式后已经无法自拔了 😁

**Comment by sxzz** [comment]
目前新文档已经更新了 `unplugin-vue-components` 的使用，对于普通用户来说似乎是一个省事的选择。
但是后续或许会有除了按需引入的其他的 feature，目前两种选择都是可以的。

**Comment by JerryWang24** [comment]
其他组件都正常，ElMessageBox这种通过js调用的样式都没有引入，请问是什么问题？

**Comment by sxzz** [comment]
@JerryWang24 `unplugin-vue-components` 仅自动导入组件相关的依赖，对于 API 需要自己导入 JS和样式
