### ISSUE TITLE
导入`ElMessage`  遇到了一点问题

### ISSUE THREAD

**Issue by mxp131011** [element-plus/unplugin-element-plus#95]
当我导入`ElMessage`  并引入对应样式时遇到了一点问题

跟`unplugin-element-plus/vite`  的 `useSource`配置有关，也许是代码逻辑弄反了，或者是一个bug，

``` js

// 正确示例1
import ElementPlusPlugin from 'unplugin-element-plus/vite';
ElementPlusPlugin() // 或者 ElementPlusPlugin({ useSource: false })
import { ElMessage } from 'element-plus';
import 'element-plus/es/components/message/style/index'; // 这里应该是导入index

// 正确示例2
import ElementPlusPlugin from 'unplugin-element-plus/vite';
ElementPlusPlugin({ useSource: true })  
import { ElMessage } from 'element-plus';
import 'element-plus/es/components/message/style/css'; //  // 这里应该是导入css

```

## 如果是向上面这样导入就是正确的，下面图片这样导入`ElMessage` 就会有部分样式不能成功导入

![image](https://user-images.githubusercontent.com/31055355/151275964-7505eb58-4d71-448b-a6b0-5fee7dd42182.png)

**Comment by mxp131011** [comment]
我在`element-plus`  也提交了一个 `issues`  https://github.com/element-plus/element-plus/issues/5632

**Comment by sxzz** [comment]
`useSource` 没发现有什么问题
